- hostname: kafka
  dname: CN=Unknown, OU=TEST, O=CONFLUENT, L=PaloAlto, S=Ca, C=US
  password: confluent
  dns:
  - localhost
  ip:
  - 127.0.0.1
  - 192.168.1.1

# - hostname: hostname1
#   dname: CN=localhost, OU=TEST, O=CONFLUENT, L=PaloAlto, S=Ca, C=US
#   dns:
#   - localhost
#   ip:
#   - 127.0.0.1
#   - 192.168.1.1
